//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/vehicle_iface_v1.h>
#include <public/capathplanner_iface_v1.h>
#include <public/capathtracker_iface_v1.h>
#include <public/ccavoidobstacles_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
rtems_task Init (uint32_t arg){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	Vehicle	comp1(1, 16, EDROOMprioVeryHigh, 1024, systemDeployment.GetComp1Memory());
	CAPathPlanner	comp2(2, 13, EDROOMprioVeryLow, 2048, systemDeployment.GetComp2Memory());
	CAPathTracker	comp3(3, 13, EDROOMprioNormal, 2048, systemDeployment.GetComp3Memory());
	CCAvoidObstacles	comp4(4, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
 
	systemDeployment.Config(&comp1, &comp2, &comp3, &comp4);
 
	systemDeployment.Start();
 
	;
 
}
