//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/vehicle_iface_v1.h>
#include <public/capathplanner_iface_v1.h>
#include <public/capathtracker_iface_v1.h>
#include <public/ccavoidobstaclesirq_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp1
	CEDROOMMessage	comp1Messages[10];
	bool	comp1MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp1QueueNodes[16];
	bool	comp1QueueNodesMarks[16];
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[13];
	bool	comp2QueueNodesMarks[13];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[13];
	bool	comp3QueueNodesMarks[13];
 
	//!Messages Memory of component comp4
	CEDROOMMessage	comp4Messages[10];
	bool	comp4MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp4QueueNodes[10];
	bool	comp4QueueNodesMarks[10];
 
	public:
 
	Vehicle::CEDROOMMemory comp1Memory;
	CAPathPlanner::CEDROOMMemory comp2Memory;
	CAPathTracker::CEDROOMMemory comp3Memory;
	CCAvoidObstaclesIRQ::CEDROOMMemory comp4Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[4];
 
	Vehicle   * mp_comp1;
	CAPathPlanner   * mp_comp2;
	CAPathTracker   * mp_comp3;
	CCAvoidObstaclesIRQ   * mp_comp4;
 
 
//!Set Components
 
	void SetComponents(Vehicle   *p_comp1,
							CAPathPlanner   *p_comp2,
							CAPathTracker   *p_comp3,
							CCAvoidObstaclesIRQ   *p_comp4);
 
 
//Signal Conversion
 
	static TEDROOMSignal C4AvoidObstaclesIRQ_PAvoidObstaclesSysCtrl__C1MainActor_PAvoidObstaclesSysCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C1MainActor_PAvoidObstaclesSysCtrl__C4AvoidObstaclesIRQ_PAvoidObstaclesSysCtrl(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2PathPlanner_PTrackPath__C3PathTracker_PTrackPath(TEDROOMSignal signal);
	static TEDROOMSignal C3PathTracker_PTrackPath__C2PathPlanner_PTrackPath(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C1MainActor_PPathTrackerCtrl__C3PathTracker_PPathTrackerCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C3PathTracker_PPathTrackerCtrl__C1MainActor_PPathTrackerCtrl(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C1MainActor_PPathPlannerCtrl__C2PathPlanner_PPathPlannerCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C2PathPlanner_PPathPlannerCtrl__C1MainActor_PPathPlannerCtrl(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	Vehicle   * mp_comp1;
	CAPathPlanner   * mp_comp2;
	CAPathTracker   * mp_comp3;
	CCAvoidObstaclesIRQ   * mp_comp4;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(Vehicle   *p_comp1,
					CAPathPlanner   *p_comp2,
					CAPathTracker   *p_comp3,
					CCAvoidObstaclesIRQ   *p_comp4);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	Vehicle::CEDROOMMemory 		* GetComp1Memory(){return &systemMemory.comp1Memory;}
	CAPathPlanner::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CAPathTracker::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
	CCAvoidObstaclesIRQ::CEDROOMMemory 		* GetComp4Memory(){return &systemMemory.comp4Memory;}
 
};
#endif
